/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "jni_md.h"

/* Header for class jscb_Msdk */

#ifndef _Included_jscb_Msdk
#define _Included_jscb_Msdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jscb_Msdk
 * Method:    sdk_main_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jscb_Msdk_sdk_1main_1init
  (JNIEnv *, jclass);

/*
 * Class:     jscb_Msdk
 * Method:    sdk_main_start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jscb_Msdk_sdk_1main_1start
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
